"""Deterministic naming conventions for DevMirror schema isolation."""

from __future__ import annotations

import re
from typing import Literal

# Two accepted DR id shapes:
#   - Legacy:  DR-<digits>       (e.g. DR-1042, hyphen-separated)
#   - Stage 4: <PREFIX><digits>  (e.g. DR00042, PROJ00042 -- auto-generated)
# Both forms are read across DevMirror; only Stage 4 form is auto-emitted.
_LEGACY_DR_NUMBER_RE = re.compile(r"^DR-(\d+)$")
# Non-greedy prefix so the digit-suffix capture grabs ALL trailing digits
# (including leading zeros from the zero-padded counter), e.g.
# 'DR00001' -> prefix 'DR', counter '00001' (not 'DR0' / '0001').
_NEW_DR_NUMBER_RE = re.compile(r"^[A-Za-z][A-Za-z0-9]{0,7}?(\d{3,12})$")


class NamingError(Exception):
    """Raised when a dr_id read from storage doesn't match either supported shape.

    Since Stage 4, dr_ids are auto-generated by the server and validated at
    HTTP route entry, so this exception should never fire during normal
    operation.  It exists as an internal-invariant guard against data
    corruption (manual control-table edits, legacy imports, future bugs).
    """


def extract_dr_number(dr_id: str) -> str:
    """Extract the numeric counter portion from a stored DR id.

    Both supported shapes are recognised:
      - Legacy hyphen form: ``DR-1042`` -> ``1042``
      - Stage 4 auto form:  ``DR00042`` / ``PROJ00042`` -> ``00042`` (counter
        with leading zeros preserved so target schema names sort lexically)

    Raises:
        NamingError: if the input matches neither shape.  Treat as a
        data-integrity bug, not a user-input validation failure -- the
        HTTP layer rejects malformed ids upstream and the database only
        ever stores server-generated ones.
    """
    m = _LEGACY_DR_NUMBER_RE.match(dr_id) or _NEW_DR_NUMBER_RE.match(dr_id)
    if not m:
        raise NamingError(
            f"Stored dr_id {dr_id!r} matches neither the legacy 'DR-<digits>' "
            "nor the auto-generated '<PREFIX><zero-padded-digits>' shape. "
            "Likely indicates a corrupted control-table row."
        )
    return m.group(1)


def dev_schema_prefix(dr_id: str) -> str:
    """Return the dev schema prefix for a DR."""
    return f"dr_{extract_dr_number(dr_id)}"


def qa_schema_prefix(dr_id: str) -> str:
    """Return the QA schema prefix for a DR."""
    return f"qa_{extract_dr_number(dr_id)}"


def schema_prefix(dr_id: str, env: Literal["dev", "qa"]) -> str:
    """Return the schema prefix for a given environment."""
    if env == "dev":
        return dev_schema_prefix(dr_id)
    if env == "qa":
        return qa_schema_prefix(dr_id)
    raise NamingError(f"Unknown environment: {env!r}. Must be 'dev' or 'qa'.")


def target_schema_fqn(
    target_catalog: str,
    prod_schema_fqn: str,
    dr_id: str,
    env: Literal["dev", "qa"],
) -> str:
    """Build a two-part target schema FQN from a production schema FQN."""
    parts = prod_schema_fqn.split(".")
    if len(parts) < 2:
        raise NamingError(
            f"prod_schema_fqn must have at least 2 dot-separated parts "
            f"(catalog.schema), got: {prod_schema_fqn!r}"
        )
    original_schema = parts[1]
    prefix = schema_prefix(dr_id, env)
    return f"{target_catalog}.{prefix}_{original_schema}"


def target_object_fqn(
    target_catalog: str,
    prod_object_fqn: str,
    dr_id: str,
    env: Literal["dev", "qa"],
) -> str:
    """Build a three-part target object FQN from a production object FQN."""
    parts = prod_object_fqn.split(".")
    if len(parts) != 3:
        raise NamingError(
            f"prod_object_fqn must be three-part (catalog.schema.object), "
            f"got: {prod_object_fqn!r}"
        )
    original_schema = parts[1]
    object_name = parts[2]
    prefix = schema_prefix(dr_id, env)
    return f"{target_catalog}.{prefix}_{original_schema}.{object_name}"


def import_schema_fqn(
    target_catalog: str,
    dr_id: str,
    env: Literal["dev", "qa"],
    suffix: str,
) -> str:
    """Build the two-part FQN of the per-DR-per-env import schema.

    Each provisioning run creates one of these schemas per source
    catalog so the customer has a known location for sideloaded
    artifacts (typically a managed Volume).  The returned FQN is
    ``<target_catalog>.<schema_prefix>_<suffix>`` -- e.g.
    ``odp_adw_ancillaries_n.dr_00042_import_main`` for dev or
    ``odp_adw_ancillaries_n.qa_00042_import_main`` for QA.

    The ``suffix`` is a deploy-time configuration value
    (``DEVMIRROR_IMPORT_SCHEMA_SUFFIX``) so different customers can
    standardise on different naming conventions.
    """
    prefix = schema_prefix(dr_id, env)
    return f"{target_catalog}.{prefix}_{suffix}"


def required_target_schemas(
    target_catalog: str,
    prod_schema_fqns: list[str],
    dr_id: str,
    env: Literal["dev", "qa"],
) -> list[str]:
    """Derive deduplicated sorted list of target schemas from prod schemas."""
    seen: set[str] = set()
    result: list[str] = []
    for fqn in prod_schema_fqns:
        target = target_schema_fqn(target_catalog, fqn, dr_id, env)
        if target not in seen:
            seen.add(target)
            result.append(target)
    result.sort()
    return result


def resolve_target_catalog(source_catalog: str, env: Literal["dev", "qa"]) -> str:
    """Map a source catalog to the target catalog for ``env``.

    Resolution order:

    1. ``DEVMIRROR_TARGET_CATALOG`` env var, if set, wins for every
       object.  This is the explicit single-target override (set via
       the per-DR ``ConfigIn.target_catalog`` field at request time).
       Use sparingly -- it forces every object in the DR into the same
       catalog regardless of its source base.
    2. Otherwise, strip any known SDLC suffix from the source to
       recover the base name and re-attach the env-specific suffix.
       Default LH suffixes are prod ``_p``, QA ``_i``, dev ``_n``:

         ``odp_adw_ancillaries_p`` + dev -> ``odp_adw_ancillaries_n``
         ``odp_adw_ancillaries_p`` + qa  -> ``odp_adw_ancillaries_i``
         ``odp_adw_ancillaries_n`` + dev -> ``odp_adw_ancillaries_n`` (idempotent)
         ``odp_adw_ancillaries_i`` + dev -> ``odp_adw_ancillaries_n`` (re-route)
         ``foo`` (no known suffix)  + dev -> ``foo_n``

    All three suffix values are configurable via env vars
    (``DEVMIRROR_PROD_CATALOG_SUFFIX``, ``DEVMIRROR_QA_CATALOG_SUFFIX``,
    ``DEVMIRROR_DEV_CATALOG_SUFFIX``).  Empty / whitespace values fall
    back to the LH defaults; only a non-blank explicit override
    replaces the default.

    Recognition (what suffixes the function strips from a source name)
    is separate from landing (where each env clones go).  By default the
    recognition set is the union of the three landing suffixes; in
    deployments where landing routes diverge from the source SDLC
    convention (LH routes both dev and QA into ``_n``, so the landing
    set is ``{_p, _n}`` -- but pre-prod sources still end in ``_i``),
    set ``DEVMIRROR_KNOWN_CATALOG_SUFFIXES`` to the comma-separated
    set of suffixes the engine should recognise on source catalogs
    (e.g. ``_p,_i,_n`` for the LH SDLC convention).
    """
    import os
    override = os.environ.get("DEVMIRROR_TARGET_CATALOG", "").strip()
    if override:
        return override
    # Empty-string env vars fall through to the default -- bundle/app.yaml
    # commonly use `value: ""` to mean "unset", and a missing suffix would
    # silently produce a catalog name with no suffix at all.
    prod_suffix = os.environ.get("DEVMIRROR_PROD_CATALOG_SUFFIX", "").strip() or "_p"
    qa_suffix = os.environ.get("DEVMIRROR_QA_CATALOG_SUFFIX", "").strip() or "_i"
    dev_suffix = os.environ.get("DEVMIRROR_DEV_CATALOG_SUFFIX", "").strip() or "_n"
    # Recognition set: explicit DEVMIRROR_KNOWN_CATALOG_SUFFIXES wins if
    # provided; otherwise fall back to the landing trio (= current behaviour).
    known_env = os.environ.get("DEVMIRROR_KNOWN_CATALOG_SUFFIXES", "").strip()
    if known_env:
        known_suffixes: tuple[str, ...] = tuple(
            s.strip() for s in known_env.split(",") if s.strip()
        )
    else:
        known_suffixes = (prod_suffix, qa_suffix, dev_suffix)
    base = source_catalog
    for s in known_suffixes:
        if base.endswith(s):
            base = base[: -len(s)]
            break
    if env == "dev":
        suffix = dev_suffix
    elif env == "qa":
        suffix = qa_suffix
    else:
        raise NamingError(
            f"Unknown environment: {env!r}. Must be 'dev' or 'qa'."
        )
    return f"{base}{suffix}"
